name: PyBOMBS Dev Image - Manual Docker Hub Push
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/pybombs-dev
          TAG: gnuradio310-ubuntu-jammy
        with:
          file: docker/pybombs-dev.dockerfile
          push: false
          platforms: linux/amd64
          build-args: |
            dist=ubuntu:jammy
            gr_version=gnuradio310
          tags: ${{ env.IMG }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.IMG }}:${{ env.TAG }}
          cache-to: type=inline